package org.example;

public enum EmprestimoStatus {
    SUCESSO,
    SUCESSO_RESERVA_ATENDIDA,
    ERRO_USUARIO_COM_PENDENCIAS,
    ERRO_LIVRO_NAO_ENCONTRADO,
    ERRO_LIVRO_RESERVADO_OUTRO_USUARIO,
    ERRO_USUARIO_JA_POSSUI_LIVRO,
    ERRO_LIVRO_INDISPONIVEL,
    ERRO_GERAL_EMPRESTIMO
}